---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12.9
  commands:
  - go test ./...

- name: build
  image: golang:1.12.9
  commands:
    - sh scripts/build.sh
  environment:
    GOARCH: amd64
    GOOS: linux
  when:
    event:
    - push
    - pull_request
    - tag

- name: publish-server
  pull: default
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.server.linux.amd64
    registry: eu.gcr.io
    repo: eu.gcr.io/unicorn-985/drone-server
    tags:
      - "${DRONE_COMMIT}"
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
      - push
      - pull_request
      - tag

- name: publish-agent
  pull: default
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.agent.linux.amd64
    registry: eu.gcr.io
    repo: eu.gcr.io/unicorn-985/drone-agent
    tags:
      - "${DRONE_COMMIT}"
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
      - push
      - pull_request
      - tag
